### ISSUE TITLE
Pawns can move in any x position in y+1

### ISSUE THREAD

**Issue by FranciscoJesusGata** [silvericarus/just-chess#8]
#2 When you drag a Pawn you can drop it in any column in the row ahead.

**Comment by silvericarus** [comment]
This is caused because the pawns only check if the x is incremented in 1 position or if both coordinates increment in 1 (Pawn moved diagonally)
This is the code: `if(Math.abs(pos_new[0]-pos_orig[0])==1 || (pos_new[0]-pos_orig[0])==1 && (pos_new[1]-pos_orig[1])==1){` On the first half  of the if check it should also check if the y stays the same, so it hasnt changed the column when changing row.

**Comment by silvericarus** [comment]
I'll check this issue and fix it
